//! Attestation Preference

use serde::{Deserialize, Serialize};

/// Specifies preference for attestation conveyance during credential generation
/// [WebAuthn Spec](https://www.w3.org/TR/webauthn/#enumdef-attestationconveyancepreference)
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum AttestationPreference {
    /// Relying Party wants to receive the attestation statement generated by the authenticator
    #[serde(rename = "direct")]
    Direct,

    /// Relying Party prefers an attestation conveyance yielding verifiable attestation statements,
    /// but allows the client to decide how to obtain such attestation statements. See spec for more
    /// details.
    #[serde(rename = "indirect")]
    Indirect,

    /// Relying Party is not interested in the autenticator attestation.
    ///
    /// Use Cases:
    /// * To potentially avoid having to obtain user consent to relay identifying information to the Relying Pary
    /// * Save a roundtrip to an Attestation CA
    #[serde(rename = "none")]
    None,
}
